### ISSUE TITLE
拼多多anti_content不对了，是不是拼多多修改了算法，大佬赐教

### ISSUE THREAD

**Issue by yzy8788** [SergioJune/Spider-Crack-JS#18]

**Comment by SergioJune** [comment]
可能修改了吧，这个暂时不更新了，已经被举报一次了，如果有需要，可以私聊

**Comment by gaoxuejian8** [comment]
大佬，怎么联系你呢？

**Comment by aiminglow** [comment]
你好，我用你的js获得的anti content已经成功请求了一些url，还有另外一些入口没成功。所以我需要自己把那些js摘出来，但是那个加密部分的太多了，所以想请教一下你debug和摘代码的经验
如果不方便在issue交流的话，这是我的邮箱，您如果方便的话能不能发一下您的联系方式？ zhangchichichichi@gmail.com

**Comment by zsljulius** [comment]
@aiminglow 我运行了大佬的pdd  js 获得的anti_content还是没法用，你怎么能用的？

**Comment by airwolf2026** [comment]
> @aiminglow 我运行了大佬的pdd js 获得的anti_content还是没法用，你怎么能用的？

返回400001是吧?

**Comment by airwolf2026** [comment]
@zsljulius 
返回40001是不是?嘿嘿

**Comment by aiminglow** [comment]
@zsljulius 我用的不是他程序里面的那个入口

**Comment by airwolf2026** [comment]
> @zsljulius 我用的不是他程序里面的那个入口

可否私信个接口?

**Comment by lwugang** [comment]
13480020053@163.com 大佬能给份资料吗

**Comment by Su-yj** [comment]
大佬，能私信一下吗？需要 anti_content 
825800608@qq.com

**Comment by Su-yj** [comment]
> [13480020053@163.com](mailto:13480020053@163.com) 大佬能给份资料吗

你知道anti_content怎样生成吗？

**Comment by Su-yj** [comment]
> [13480020053@163.com](mailto:13480020053@163.com) 大佬能给份资料吗

@lwugang 你现在能找到 anti_content 的生成方法吗？

**Comment by SergioJune** [comment]
我知道，只不过有偿哈，不公开了，资料就是看我的文章，已经很详细了，也有很多人看这个学会了




------------------ 原始邮件 ------------------
发件人: "Su-yj"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 晚上11:51
收件人: "SergioJune/Spider-Crack-JS"<Spider-Crack-JS@noreply.github.com>; 
抄送: "　　　　　　"<2217532592@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [SergioJune/Spider-Crack-JS] 拼多多anti_content不对了，是不是拼多多修改了算法，大佬赐教 (#18)



 
13480020053@163.com 大佬能给份资料吗
  
你知道anti_content怎样生成吗？

**Comment by SergioJune** [comment]
可以啊，如果需要的话，可以加我qq2217532592详谈




------------------ 原始邮件 ------------------
发件人: "Su-yj"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 晚上11:52
收件人: "SergioJune/Spider-Crack-JS"<Spider-Crack-JS@noreply.github.com>; 
抄送: "　　　　　　"<2217532592@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [SergioJune/Spider-Crack-JS] 拼多多anti_content不对了，是不是拼多多修改了算法，大佬赐教 (#18)



 
13480020053@163.com 大佬能给份资料吗
  
@lwugang 你现在能找到 anti_content 的生成方法吗？

**Comment by SergioJune** [comment]
已更新
