### ISSUE TITLE
pdd的我用js生成的 anti_content 请求接口未获取到数据

### ISSUE THREAD

**Issue by hhb18720627130** [SergioJune/Spider-Crack-JS#30]
{"server_time":1556600325,"verify_auth_token":"bV3UnUHXQZrd4tI2-qH2gg","scene_id":11,"error_code":54001}  返回的是这样的提示

**Comment by SergioJune** [comment]
这个证明需要过验证码，过了验证码之后就可以有数据了，可以自己去浏览器抓包看看就知道了
