### ISSUE TITLE
pdd-token

### ISSUE THREAD

**Issue by sunzhixianbj** [SergioJune/Spider-Crack-JS#34]
大佬 有说代码改了需要添加cookie了 不知道能不能更新下 弄了好久都没有调试出来

**Comment by SergioJune** [comment]
这个添加cookie也没用，现在拼多多是这样的，第一次访问页数返回错误的话，证明需要验证码，这个不在本范围内，换IP好像也没有用，一定要处理这个验证码，后面才会有数据出现，而且只需要处理一次即可，后面会根据爬取速度再取
