### ISSUE TITLE
关于脚本运行无法获取list-id和flip

### ISSUE THREAD

**Issue by Voccoo** [SergioJune/Spider-Crack-JS#8]
现给出的requests访问第一个url，必须挂cookie在header中，才可获取到含有list_id和flip的页面。

**Comment by SergioJune** [comment]
我的代码可以正常获取，不需要挂cookie也行，不过好像我这里的代码有个问题，我过两天更新下

**Comment by SergioJune** [comment]
pdd的已更新了，现在可以正常获取了
